package collectiva.org.collecta.enums;

public enum CategoriaCampanha {
    SAUDE, EDUCACAO, MEIO_AMBIENTE, ARRECADACAO_DE_FUNDOS, CULTURA_E_ARTE, AJUDA_HUMANITARIA, ESPORTES,
    TECNOLOGIA, ANIMAIS, CRIANCAS, IDOSOS, ALIMENTACAO, HABITACAO, EMPREENDEDORISMO, IGUALDADE_DE_GENERO,
    COMBATE_A_POBREZA, SAUDE_MENTAL, INOVACAO_SOCIAL, OUTROS
}
